# Generated by Django 4.1.5 on 2023-01-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=50)),
                ("job_title", models.CharField(max_length=50)),
                ("post_date", models.DateField(auto_now_add=True)),
                ("closing_date", models.DateField()),
                ("location", models.CharField(max_length=50)),
                ("details", models.TextField()),
            ],
        ),
    ]
